### ISSUE TITLE
Steam error clipboard

### ISSUE THREAD

**Issue by Firathmagi** [acegiak/AshQudPolearms#1]
=== Polearms Errors ===
<...>\steamapps\workshop\content\333640\1746875916\EffectGripped.cs(35,44): error CS1061: 'Physics' does not contain a definition for 'bUsesTwoSlots' and no accessible extension method 'bUsesTwoSlots' accepting a first argument of type 'Physics' could be found (are you missing a using directive or an assembly reference?)
<...>\steamapps\workshop\content\333640\1746875916\EffectGripped.cs(40,33): error CS1061: 'Physics' does not contain a definition for 'bUsesTwoSlots' and no accessible extension method 'bUsesTwoSlots' accepting a first argument of type 'Physics' could be found (are you missing a using directive or an assembly reference?)
<...>\steamapps\workshop\content\333640\1746875916\EffectGripped.cs(54,33): error CS1061: 'Physics' does not contain a definition for 'bUsesTwoSlots' and no accessible extension method 'bUsesTwoSlots' accepting a first argument of type 'Physics' could be found (are you missing a using directive or an assembly reference?)
<...>\steamapps\workshop\content\333640\1746875916\PolearmGrip.cs(70,9): error CS0246: The type or namespace name 'BodyPart' could not be found (are you missing a using directive or an assembly reference?)
<...>\steamapps\workshop\content\333640\1746875916\PolearmGrip.cs(70,35): error CS0029: Cannot implicitly convert type 'System.Collections.Generic.List<XRL.World.Anatomy.BodyPart>' to 'System.Collections.Generic.List<BodyPart>'
<...>\steamapps\workshop\content\333640\1746875916\PolearmGrip.cs(71,13): error CS0246: The type or namespace name 'BodyPart' could not be found (are you missing a using directive or an assembly reference?)
<...>\steamapps\workshop\content\333640\1746875916\PolearmRepel.cs(67,9): error CS0246: The type or namespace name 'BodyPart' could not be found (are you missing a using directive or an assembly reference?)
<...>\steamapps\workshop\content\333640\1746875916\PolearmLunge.cs(39,9): error CS0246: The type or namespace name 'BodyPart' could not be found (are you missing a using directive or an assembly reference?)
<...>\steamapps\workshop\content\333640\1746875916\PolearmLunge.cs(39,35): error CS0029: Cannot implicitly convert type 'System.Collections.Generic.List<XRL.World.Anatomy.BodyPart>' to 'System.Collections.Generic.List<BodyPart>'
<...>\steamapps\workshop\content\333640\1746875916\PolearmLunge.cs(40,13): error CS0246: The type or namespace name 'BodyPart' could not be found (are you missing a using directive or an assembly reference?)
<...>\steamapps\workshop\content\333640\1746875916\PolearmRepel.cs(67,35): error CS0029: Cannot implicitly convert type 'System.Collections.Generic.List<XRL.World.Anatomy.BodyPart>' to 'System.Collections.Generic.List<BodyPart>'
<...>\steamapps\workshop\content\333640\1746875916\PolearmRepel.cs(68,13): error CS0246: The type or namespace name 'BodyPart' could not be found (are you missing a using directive or an assembly reference?)
<...>\steamapps\workshop\content\333640\1746875916\PolearmGrip.cs(88,5): error CS0246: The type or namespace name 'BodyPart' could not be found (are you missing a using directive or an assembly reference?)
== Warnings ==
<...>\steamapps\workshop\content\333640\1746875916\ReachPart.cs(14,4): warning CS0618: 'IPart.Name.set' is obsolete: 'No longer settable, reads from Type of Part - Will be removed Q2 2023'
<...>\steamapps\workshop\content\333640\1746875916\PolearmGrip.cs(68,8): warning CS0219: The variable 'num' is assigned but its value is never used
<...>\steamapps\workshop\content\333640\1746875916\PolearmLunge.cs(37,8): warning CS0219: The variable 'num' is assigned but its value is never used
<...>\steamapps\workshop\content\333640\1746875916\PolearmRepel.cs(65,8): warning CS0219: The variable 'num' is assigned but its value is never used
<...>\steamapps\workshop\content\333640\1746875916\PolearmLunge.cs(121,9): warning CS0219: The variable 'num2' is assigned but its value is never used
<...>\steamapps\workshop\content\333640\1746875916\PolearmLunge.cs(144,9): warning CS0219: The variable 'num3' is assigned but its value is never used

**Comment by acegiak** [comment]
This should have been fixed by this update : https://github.com/acegiak/AshQudPolearms/commit/10712fe0c49b5de0b442562c812548bafb65f2db which was uploaded to Steam on 2023-02-13. Double check you have the latest version from the workshop or update from this repo now that the change has been pushed here?

**Comment by Firathmagi** [comment]
only just subscribed to the steam version. cant really make heads nor tales
of how to check the version info

**Comment by Firathmagi** [comment]
also still cant make heads nor tails of what im supposed to do with github
nor new email interfaces anymore
